# Generated by Django 3.2.12 on 2022-05-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=100)),
                ('body', models.JSONField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
