# Generated by Django 3.2.12 on 2022-05-26 13:11

from django.db import migrations, models
import src.apps.outbox.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id not sequential using UUID Field', primary_key=True, serialize=False, unique=True)),
                ('version', models.CharField(default='v1', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('content', models.JSONField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=src.apps.outbox.models._one_more_day)),
                ('retry', models.PositiveIntegerField(default=50)),
                ('status', models.IntegerField(choices=[(-1, 'Failed'), (1, 'Schedule'), (2, 'Succeeded')], default=1)),
            ],
            options={
                'verbose_name': 'published',
            },
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id not sequential using UUID Field', primary_key=True, serialize=False, unique=True)),
                ('version', models.CharField(default='v1', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100, null=True)),
                ('content', models.JSONField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=src.apps.outbox.models._one_more_day)),
                ('retry', models.PositiveIntegerField(default=50)),
                ('status', models.IntegerField(choices=[(-1, 'Failed'), (1, 'Schedule'), (2, 'Succeeded')], default=1)),
            ],
            options={
                'verbose_name': 'received',
            },
        ),
    ]
